$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
Set-Location $repoRoot

function Test-ActivePaperBatch {
    $running = Get-CimInstance Win32_Process -Filter "name = 'python.exe'" | Where-Object {
        $commandLine = $_.CommandLine -replace [char]34, ""
        $commandLine -notlike "* -Command *" -and $commandLine -like "*main.py paper-batch*"
    }
    return [bool]$running
}

if (Test-ActivePaperBatch) {
    Write-Host "Skipping readiness refresh while a paper-batch process is active; post-queue finalization will refresh it."
    exit 0
}

python main.py strict-baseline-guard --protocol-dir artifacts/strict_baseline_protocol_wtb_strictmask_20260609 --output-dir artifacts/strict_baseline_protocol_wtb_strictmask_20260609/guard_refresh --root-dir . --cache-root artifacts/cache_strictmask --suite-dir artifacts/strictmask_baseline_rerun_wtb_full --train-days 180 --val-days 30 --test-days 35 --hist-len 36 --pred-len 24 --variant-keys graph_wavenet,graph_transformer,gat_gru,patchtst --seeds 201,202,203,204,205
python main.py future-holdout-guard --protocol-dir artifacts/future_holdout_protocol_wtb_strictmask_20260609 --output-dir artifacts/future_holdout_protocol_wtb_strictmask_20260609/guard_refresh --root-dir . --cache-root artifacts/cache_strictmask_future --train-days 160 --val-days 25 --test-days 25 --holdout-days 35 --hist-len 36 --pred-len 24
python main.py future-holdout-evidence-guard --protocol-dir artifacts/future_holdout_protocol_wtb_strictmask_20260609 --output-dir artifacts/future_holdout_evidence_guard_wtb_strictmask --suite-dir artifacts/future_holdout_wtb_strictmask_runs --cache-dir artifacts/cache_strictmask_future/wtb_245d --mechanism-dir artifacts/future_holdout_wtb_strictmask_mechanism_gate --placebo-dir artifacts/future_holdout_wtb_strictmask_placebo --boundary-slice-dir artifacts/future_holdout_wtb_strictmask_boundary_slice --reviewer-pack-dir artifacts/future_holdout_wtb_strictmask_reviewer_stats --seeds 301,302,303,304,305
python main.py spatial-holdout-guard --protocol-dir artifacts/spatial_holdout_protocol_wtb_east_20260611 --output-dir artifacts/spatial_holdout_protocol_wtb_east_20260611/guard_refresh --source-cache-dir artifacts/cache_strictmask/wtb_245d --output-cache-root artifacts/cache_strictmask_spatial_east --suite-dir artifacts/spatial_holdout_wtb_east_runs --strategy east --fraction 0.2 --seeds 401,402,403,404,405 --variant-keys bal_align_force,context_align_force,anchor_only
python main.py spatial-holdout-evidence-guard --protocol-dir artifacts/spatial_holdout_protocol_wtb_east_20260611 --output-dir artifacts/spatial_holdout_evidence_guard_wtb_east --suite-dir artifacts/spatial_holdout_wtb_east_runs --cache-dir artifacts/cache_strictmask_spatial_east/wtb_245d --mechanism-dir artifacts/spatial_holdout_wtb_east_mechanism_gate --reviewer-pack-dir artifacts/spatial_holdout_wtb_east_reviewer_stats --seeds 401,402,403,404,405 --variant-keys bal_align_force,context_align_force,anchor_only
python main.py strict-ablation-guard --output-dir artifacts/strict_ablation_guard_wtb_strictmask --root-dir . --cache-root artifacts/cache_strictmask --suite-dir artifacts/strictmask_ablation_rerun_wtb_full --train-days 180 --val-days 30 --test-days 35 --hist-len 36 --pred-len 24 --variant-keys dense,unconstrained,bal,align,bal_align,bal_align_force,bal_align_force_smooth,context_align_force,anchor_only,full --seeds 201,202,203,204,205
python main.py strict-ablation-evidence-guard --output-dir artifacts/strict_ablation_evidence_guard_wtb_strictmask --root-dir . --cache-root artifacts/cache_strictmask --suite-dir artifacts/strictmask_ablation_rerun_wtb_full --routing-gate-dir artifacts/strictmask_ablation_routing_controls_gate --train-days 180 --val-days 30 --test-days 35 --hist-len 36 --pred-len 24 --variant-keys dense,unconstrained,bal,align,bal_align,bal_align_force,bal_align_force_smooth,context_align_force,anchor_only,full --seeds 201,202,203,204,205 --gate-variant-keys bal_align_force,context_align_force,anchor_only
python main.py threshold-controls-guard --output-dir artifacts/strict_threshold_controls_guard_wtb_strictmask --root-dir . --cache-root artifacts/cache_strictmask --suite-dir artifacts/strictmask_threshold_controls_wtb --train-days 180 --val-days 30 --test-days 35 --hist-len 36 --pred-len 24 --variant-keys sens_rated_7p0,sens_rated_13p0,sens_pitch_0p5,sens_pitch_20p0 --seeds 201,202,203,204,205
python main.py paper-export --dataset wtb --root-dir . --cache-root artifacts/cache_strictmask --output-dir artifacts/strictmask_threshold_controls_mechanism_source --wtb-suite-dir artifacts/strictmask_threshold_controls_wtb
python main.py mechanism-intervention --run-table artifacts/strictmask_threshold_controls_mechanism_source/tables/wtb_test_aggregated_runs.csv --cache-dir artifacts/cache_strictmask/wtb_245d --output-dir artifacts/strictmask_threshold_controls_mechanism --root-dir . --split test --models "Physics-Aligned MoE" --interventions actual,anchor_boundary_zero --batch-size 512
python main.py threshold-controls-semantic-guard --output-dir artifacts/strict_threshold_controls_semantic_guard_wtb_strictmask --mechanism-dir artifacts/strictmask_threshold_controls_mechanism --positive-mechanism-dir artifacts/mechanism_gate_wtb_strictmask_full/mechanism_intervention --variant-keys sens_rated_7p0,sens_rated_13p0,sens_pitch_0p5,sens_pitch_20p0 --seeds 201,202,203,204,205
python main.py threshold-controls-evidence-guard --output-dir artifacts/strict_threshold_controls_evidence_guard_wtb_strictmask --root-dir . --cache-root artifacts/cache_strictmask --suite-dir artifacts/strictmask_threshold_controls_wtb --reviewer-pack-dir artifacts/strictmask_threshold_controls_reviewer_stats --semantic-guard-dir artifacts/strict_threshold_controls_semantic_guard_wtb_strictmask --boundary-negative-guard-dir artifacts/boundary_negative_controls_wtb --train-days 180 --val-days 30 --test-days 35 --hist-len 36 --pred-len 24 --variant-keys sens_rated_7p0,sens_rated_13p0,sens_pitch_0p5,sens_pitch_20p0 --seeds 201,202,203,204,205
python main.py threshold-label-validity-audit --dataset wtb --root-dir . --cache-dir artifacts/cache_strictmask/wtb_245d --run-table artifacts/strictmask_combined_reviewer_stats/reviewer_stat_pack_run_table.csv --output-dir artifacts/threshold_label_validity_audit_wtb_strictmask --models "MoE + L_bal + L_align + L_force" --rated-wind-grid 10.0,10.5,11.0 --pitch-threshold-grid 1.5,2.0,2.5 --seeds 201,202,203,204,205
python main.py reviewer-stat-pack-guard --pack-dir artifacts/strictmask_combined_reviewer_stats --output-dir artifacts/strictmask_combined_reviewer_stats_guard --min-runs 35
python main.py science-readiness-dashboard --output-dir artifacts/science_readiness_dashboard_20260611 --root-dir . --threshold-controls-evidence-guard artifacts/strict_threshold_controls_evidence_guard_wtb_strictmask/threshold_controls_evidence_guard.json --reviewer-pack-guard artifacts/strictmask_combined_reviewer_stats_guard/reviewer_stat_pack_guard.json --reviewer-pack-config artifacts/strictmask_combined_reviewer_stats/reviewer_stat_pack_config.json --external-wind-guard artifacts/external_wind_guard/external_wind_guard.json --external-wind-source-guard artifacts/external_wind_source_guard/external_wind_source_guard.json --final-evidence-manifest artifacts/final_evidence_package/manifest/evidence_manifest_final.json --reproducibility-manifest artifacts/reproducibility_manifest_final/reproducibility_manifest.json
python main.py reproducibility-manifest --output-dir artifacts/reproducibility_manifest_final --root-dir . --hash-max-mb 25
python main.py science-readiness-dashboard --output-dir artifacts/science_readiness_dashboard_20260611 --root-dir . --threshold-controls-evidence-guard artifacts/strict_threshold_controls_evidence_guard_wtb_strictmask/threshold_controls_evidence_guard.json --reviewer-pack-guard artifacts/strictmask_combined_reviewer_stats_guard/reviewer_stat_pack_guard.json --reviewer-pack-config artifacts/strictmask_combined_reviewer_stats/reviewer_stat_pack_config.json --external-wind-guard artifacts/external_wind_guard/external_wind_guard.json --external-wind-source-guard artifacts/external_wind_source_guard/external_wind_source_guard.json --final-evidence-manifest artifacts/final_evidence_package/manifest/evidence_manifest_final.json --reproducibility-manifest artifacts/reproducibility_manifest_final/reproducibility_manifest.json

Get-Content artifacts\science_readiness_dashboard_20260611\README.md
