python main.py external-wind-preprocess --root-dir . --external-source-dir data\external_wind --farm kelmarsh --external-split chronological --cache-root artifacts\cache_external_wind
python main.py paper-batch --dataset external_wind --root-dir . --external-source-dir data\external_wind --farm kelmarsh --external-split chronological --cache-root artifacts\cache_external_wind --output-dir artifacts\external_wind_runs\kelmarsh\chronological --groups main --variant-keys full --seeds 201,202,203,204,205 --epochs 20 --batch-size 16 --hidden-dim 64 --skip-visuals
python main.py paper-batch --dataset external_wind --root-dir . --external-source-dir data\external_wind --farm kelmarsh --external-split chronological --cache-root artifacts\cache_external_wind --output-dir artifacts\external_wind_runs\kelmarsh\chronological --groups ablation --variant-keys bal_align_force --seeds 201,202,203,204,205 --epochs 20 --batch-size 16 --hidden-dim 64 --skip-visuals
python main.py paper-batch --dataset external_wind --root-dir . --external-source-dir data\external_wind --farm kelmarsh --external-split chronological --cache-root artifacts\cache_external_wind --output-dir artifacts\external_wind_runs\kelmarsh\chronological --groups strong_baselines --variant-keys graph_wavenet,patchtst --seeds 201,202,203,204,205 --strong-baseline-seeds 201,202,203,204,205 --epochs 20 --batch-size 16 --hidden-dim 64 --skip-visuals
python main.py external-wind-preprocess --root-dir . --external-source-dir data\external_wind --farm kelmarsh --external-split leave-one-farm-out --external-target-farm penmanshiel --cache-root artifacts\cache_external_wind
python main.py paper-batch --dataset external_wind --root-dir . --external-source-dir data\external_wind --farm kelmarsh --external-split leave-one-farm-out --external-target-farm penmanshiel --cache-root artifacts\cache_external_wind --output-dir artifacts\external_wind_runs\kelmarsh\leave_one_farm_out --groups main --variant-keys full --seeds 201,202,203,204,205 --epochs 20 --batch-size 16 --hidden-dim 64 --skip-visuals
python main.py paper-batch --dataset external_wind --root-dir . --external-source-dir data\external_wind --farm kelmarsh --external-split leave-one-farm-out --external-target-farm penmanshiel --cache-root artifacts\cache_external_wind --output-dir artifacts\external_wind_runs\kelmarsh\leave_one_farm_out --groups ablation --variant-keys bal_align_force --seeds 201,202,203,204,205 --epochs 20 --batch-size 16 --hidden-dim 64 --skip-visuals
python main.py paper-batch --dataset external_wind --root-dir . --external-source-dir data\external_wind --farm kelmarsh --external-split leave-one-farm-out --external-target-farm penmanshiel --cache-root artifacts\cache_external_wind --output-dir artifacts\external_wind_runs\kelmarsh\leave_one_farm_out --groups strong_baselines --variant-keys graph_wavenet,patchtst --seeds 201,202,203,204,205 --strong-baseline-seeds 201,202,203,204,205 --epochs 20 --batch-size 16 --hidden-dim 64 --skip-visuals
python main.py external-wind-preprocess --root-dir . --external-source-dir data\external_wind --farm penmanshiel --external-split chronological --cache-root artifacts\cache_external_wind
python main.py paper-batch --dataset external_wind --root-dir . --external-source-dir data\external_wind --farm penmanshiel --external-split chronological --cache-root artifacts\cache_external_wind --output-dir artifacts\external_wind_runs\penmanshiel\chronological --groups main --variant-keys full --seeds 201,202,203,204,205 --epochs 20 --batch-size 16 --hidden-dim 64 --skip-visuals
python main.py paper-batch --dataset external_wind --root-dir . --external-source-dir data\external_wind --farm penmanshiel --external-split chronological --cache-root artifacts\cache_external_wind --output-dir artifacts\external_wind_runs\penmanshiel\chronological --groups ablation --variant-keys bal_align_force --seeds 201,202,203,204,205 --epochs 20 --batch-size 16 --hidden-dim 64 --skip-visuals
python main.py paper-batch --dataset external_wind --root-dir . --external-source-dir data\external_wind --farm penmanshiel --external-split chronological --cache-root artifacts\cache_external_wind --output-dir artifacts\external_wind_runs\penmanshiel\chronological --groups strong_baselines --variant-keys graph_wavenet,patchtst --seeds 201,202,203,204,205 --strong-baseline-seeds 201,202,203,204,205 --epochs 20 --batch-size 16 --hidden-dim 64 --skip-visuals
python main.py external-wind-preprocess --root-dir . --external-source-dir data\external_wind --farm penmanshiel --external-split leave-one-farm-out --external-target-farm kelmarsh --cache-root artifacts\cache_external_wind
python main.py paper-batch --dataset external_wind --root-dir . --external-source-dir data\external_wind --farm penmanshiel --external-split leave-one-farm-out --external-target-farm kelmarsh --cache-root artifacts\cache_external_wind --output-dir artifacts\external_wind_runs\penmanshiel\leave_one_farm_out --groups main --variant-keys full --seeds 201,202,203,204,205 --epochs 20 --batch-size 16 --hidden-dim 64 --skip-visuals
python main.py paper-batch --dataset external_wind --root-dir . --external-source-dir data\external_wind --farm penmanshiel --external-split leave-one-farm-out --external-target-farm kelmarsh --cache-root artifacts\cache_external_wind --output-dir artifacts\external_wind_runs\penmanshiel\leave_one_farm_out --groups ablation --variant-keys bal_align_force --seeds 201,202,203,204,205 --epochs 20 --batch-size 16 --hidden-dim 64 --skip-visuals
python main.py paper-batch --dataset external_wind --root-dir . --external-source-dir data\external_wind --farm penmanshiel --external-split leave-one-farm-out --external-target-farm kelmarsh --cache-root artifacts\cache_external_wind --output-dir artifacts\external_wind_runs\penmanshiel\leave_one_farm_out --groups strong_baselines --variant-keys graph_wavenet,patchtst --seeds 201,202,203,204,205 --strong-baseline-seeds 201,202,203,204,205 --epochs 20 --batch-size 16 --hidden-dim 64 --skip-visuals
