$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
Set-Location $repoRoot

python main.py strict-evidence-export --dataset wtb --root-dir . --output-dir artifacts/strict_wtb_evidence_sources_20260609 --strict-suite-dir artifacts/strictmask_validation_wtb_full --mechanism-dir artifacts/mechanism_gate_wtb_strictmask_full --placebo-dir artifacts/routing_placebo_wtb_strictmask_full --time-forward-dir artifacts/time_forward_wtb_strictmask_full --boundary-slice-dir artifacts/boundary_slice_wtb_strictmask_full --model "MoE + L_bal + L_align + L_force"
python main.py paper-export --dataset wtb --root-dir . --cache-root artifacts/cache_strictmask --output-dir artifacts/strictmask_threshold_controls_mechanism_source --wtb-suite-dir artifacts/strictmask_threshold_controls_wtb
python main.py mechanism-intervention --run-table artifacts/strictmask_threshold_controls_mechanism_source/tables/wtb_test_aggregated_runs.csv --cache-dir artifacts/cache_strictmask/wtb_245d --output-dir artifacts/strictmask_threshold_controls_mechanism --root-dir . --split test --models "Physics-Aligned MoE" --interventions actual,anchor_boundary_zero --batch-size 512
python main.py threshold-controls-semantic-guard --output-dir artifacts/strict_threshold_controls_semantic_guard_wtb_strictmask --mechanism-dir artifacts/strictmask_threshold_controls_mechanism --positive-mechanism-dir artifacts/mechanism_gate_wtb_strictmask_full/mechanism_intervention --variant-keys sens_rated_7p0,sens_rated_13p0,sens_pitch_0p5,sens_pitch_20p0 --seeds 201,202,203,204,205
python main.py threshold-controls-evidence-guard --output-dir artifacts/strict_threshold_controls_evidence_guard_wtb_strictmask --root-dir . --cache-root artifacts/cache_strictmask --suite-dir artifacts/strictmask_threshold_controls_wtb --reviewer-pack-dir artifacts/strictmask_threshold_controls_reviewer_stats --semantic-guard-dir artifacts/strict_threshold_controls_semantic_guard_wtb_strictmask --boundary-negative-guard-dir artifacts/boundary_negative_controls_wtb --train-days 180 --val-days 30 --test-days 35 --hist-len 36 --pred-len 24 --variant-keys sens_rated_7p0,sens_rated_13p0,sens_pitch_0p5,sens_pitch_20p0 --seeds 201,202,203,204,205
python main.py operational-baselines --dataset wtb --root-dir . --cache-dir artifacts/cache_strictmask/wtb_245d --output-dir artifacts/operational_baselines_wtb_strictmask --baselines persistence,power_curve,xgboost_lag,lightgbm_lag,dlinear --max-train-samples 120000 --max-dlinear-samples 80000 --tree-estimators 80 --seed 42
python main.py reserve-decision --dataset wtb --root-dir . --run-table artifacts/strictmask_combined_reviewer_stats/reviewer_stat_pack_run_table.csv --cache-dir artifacts/cache_strictmask/wtb_245d --output-dir artifacts/decision_reserve_wtb_operational_windows --strata boundary,non_boundary,late_period --bootstrap-samples 1000 --skip-plots
python main.py reserve-decision-guard --dataset wtb --root-dir . --decision-dir artifacts/decision_reserve_wtb_operational_windows --output-dir artifacts/decision_reserve_wtb_operational_windows_guard --required-models "Graph WaveNet,PatchTST,Physics-Aligned MoE,Boundary-forced router" --required-seeds 201,202,203,204,205 --min-bootstrap-rows 9 --min-seed-day-pairs 5
# capped preview for reviewer-facing package. Run generate_uncapped_per_example_reviewer_stats.ps1 for the full per-example table.
python main.py reviewer-stat-pack --dataset wtb --root-dir . --output-dir artifacts/strictmask_combined_reviewer_stats --suite-dir artifacts/strictmask_validation_wtb_full --suite-dir artifacts/strictmask_baseline_rerun_wtb_full --suite-dir artifacts/strictmask_ablation_rerun_wtb_full --cache-dir artifacts/cache_strictmask/wtb_245d --split test --models "Graph WaveNet,PatchTST,Physics-Aligned MoE,MoE + L_bal + L_align + L_force" --reference-model "MoE + L_bal + L_align + L_force" --baseline-models "Graph WaveNet,PatchTST,Physics-Aligned MoE" --bootstrap-samples 1000 --permutation-samples 1000 --max-per-example-rows 200000 --max-paired-examples 100000 --top-k-failures 24
python main.py reviewer-stat-pack-guard --pack-dir artifacts/strictmask_combined_reviewer_stats --output-dir artifacts/strictmask_combined_reviewer_stats_guard --min-runs 20 --required-models "Graph WaveNet,PatchTST,Physics-Aligned MoE,MoE + L_bal + L_align + L_force" --required-seeds 201,202,203,204,205
python main.py reproducibility-manifest --output-dir artifacts/reproducibility_manifest_final --root-dir . --hash-max-mb 25
powershell -ExecutionPolicy Bypass -File artifacts\science_readiness_dashboard_20260611\refresh_readiness.ps1
powershell -ExecutionPolicy Bypass -File artifacts\reproduction_package_20260611\rebuild_final_evidence_package.ps1
